[package]
name = "presenie"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
ooxmlsdk = { git = "https://github.com/KaiserY/ooxmlsdk", version = "0.2.0", features = ["parts"] }
